version: '3.8'

services:
# Наш модуль предсказания пожаров по спутниковым данным
  fire-predict-api:
      build:
        context: ./fire_predict_module
      container_name: fire_predict_api
      ports:
        - "8001:8001"
      networks:
        - app-network
# Потом дополню, если что-то изменится касательно back и front
  backend:
    build:
      context: ./backend
    container_name: firedetect_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: firedetect_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
